### ISSUE TITLE
Error when running "Install colmap" in colab

### ISSUE THREAD

**Issue by khanhpham3799** [kwea123/nerf_pl#152]
I try to preprocess by my own data but got this issue: 
/content/LLFF
Need to run COLMAP
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/content/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'colmap': 'colmap'

**Comment by 88ili88** [comment]
I had the same issue

**Comment by austenjs** [comment]
I think this issue is the same as https://github.com/kwea123/nerf_pl/issues/147
