### ISSUE TITLE
Colmap UnicodeDecodeError

### ISSUE THREAD

**Issue by BoujlidaMohamed** [kwea123/nerf_pl#155]
I am using colmpa on  a custom data  and when I try 
`!python imgs2poses.py "/content/experiement"`

I get the next error
`/content/LLFF
Need to run COLMAP
Features extracted
Features matched
Sparse map created
Finished running COLMAP, see /content/experiement/colmap_output.txt for logs
Post-colmap
Cameras 5
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 274, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/content/LLFF/llff/poses/pose_utils.py", line 26, in load_colmap_data
    imdata = read_model.read_images_binary(imagesfile)
  File "/content/LLFF/llff/poses/colmap_read_model.py", line 187, in read_images_binary
    image_name += current_char.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 0: unexpected end of data`
Does anyone knows how to fix it ?

**Comment by imadgohar** [comment]
How you done with the colmap installation, I am stuck there, METIS Libraries are missing or declared as unfound, trying to locate the file.

**Comment by BoujlidaMohamed** [comment]
@imadgohar  @kwea123 
I was able to solve the problem , it was the ceres solver's version problem 
change the ceres solver part to this in the notebook and it should work 
`!sudo apt-get install libatlas-base-dev libsuitesparse-dev`
`!git clone --depth 1 --branch 2.1.0 https://github.com/ceres-solver/ceres-solver.git `
`%cd ceres-solver`
`!git checkout $(git describe --tags) # Checkout the latest release`
`%mkdir build`
`%cd build`
`!cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF`
`!make -j4`
`!sudo make install`

**Comment by BoujlidaMohamed** [comment]
@imadgohar @kwea123  I still haven't solved this, apparently it depends on what kind of data I am using
