### ISSUE TITLE
Failed to train self dataset with nerf_w

### ISSUE THREAD

**Issue by ucbq466** [kwea123/nerf_pl#161]
Thanks for your repo! There comes an issue when I train my own dataset with nerf_w. It seems like the torch has something wrong, but I don't have an idea about why, could you help me with that? Many thanks!

python train.py --root_dir F:\NeRF\cenotaph --dataset_name phototourism --img_downscale 8 --use_cache --N_importance 64 --N_samples 64 --encode_a --encode_t --beta_min 0.03 --N_vocab 150 --N_emb_xyz 15 --num_epochs 20 --batch_size 1024 --optimizer adam --lr 5e-4 --lr_scheduler cosine --exp_name cenotaph_scale8_nerfw

Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main(hparams)
  File "train.py", line 184, in main
    system = NeRFSystem(hparams)
  File "train.py", line 31, in __init__
    self.hparams = hparams
  File "F:\NeRF\Anaconda3\envs\nerf_pl\lib\site-packages\torch\nn\modules\module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by JNH-LD** [comment]
Same issue, can anyone solve it?

**Comment by JNH-LD** [comment]
self.save_hyperparameters(hparams)

**Comment by szgy66** [comment]
> Thanks for your repo! There comes an issue when I train my own dataset with nerf_w. It seems like the torch has something wrong, but I don't have an idea about why, could you help me with that? Many thanks!
> 
> python train.py --root_dir F:\NeRF\cenotaph --dataset_name phototourism --img_downscale 8 --use_cache --N_importance 64 --N_samples 64 --encode_a --encode_t --beta_min 0.03 --N_vocab 150 --N_emb_xyz 15 --num_epochs 20 --batch_size 1024 --optimizer adam --lr 5e-4 --lr_scheduler cosine --exp_name cenotaph_scale8_nerfw
> 
> Traceback (most recent call last): File "train.py", line 215, in main(hparams) File "train.py", line 184, in main system = NeRFSystem(hparams) File "train.py", line 31, in **init** self.hparams = hparams File "F:\NeRF\Anaconda3\envs\nerf_pl\lib\site-packages\torch\nn\modules\module.py", line 1225, in **setattr** object.**setattr**(self, name, value) AttributeError: can't set attribute

Hello, I also plan to use Nerf_w to train my own data set recently, but I don't know how to prepare my data, any suggestions please? thank you!

**Comment by jinhyunk** [comment]
I have same issue with you. I'm still waiting for solutions..

**Comment by wtj-zhong** [comment]
I also have same issue with you. I'm still waiting for solutions..

**Comment by ShineiArakawa** [comment]
It seems this issue is related to PyTorch Lightning. The `LightningModule` already has a property named `hparams`, and direct assignment to it is not allowed. You can resolve this by renaming `self.hparams` to something else, like `self.opts`.
