### ISSUE TITLE
nerf colab run with error

### ISSUE THREAD

**Issue by JianingHe0115** [kwea123/nerf_pl#202]
When I run the in installation part of the nerf in colab, there are some error about the torch version.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.4.0

And I change the torch version, there are some error about training part:
/content/nerf_pl
Traceback (most recent call last):
  File "/content/nerf_pl/train.py", line 7, in <module>
    from datasets import dataset_dict
  File "/content/nerf_pl/datasets/__init__.py", line 1, in <module>
    from .blender import BlenderDataset
  File "/content/nerf_pl/datasets/blender.py", line 9, in <module>
    from .ray_utils import *
  File "/content/nerf_pl/datasets/ray_utils.py", line 2, in <module>
    from kornia import create_meshgrid
  File "/usr/local/lib/python3.9/dist-packages/kornia/__init__.py", line 12, in <module>
    from kornia import augmentation
  File "/usr/local/lib/python3.9/dist-packages/kornia/augmentation/__init__.py", line 1, in <module>
    from .augmentation import *
  File "/usr/local/lib/python3.9/dist-packages/kornia/augmentation/augmentation.py", line 7, in <module>
    from . import functional as F
  File "/usr/local/lib/python3.9/dist-packages/kornia/augmentation/functional.py", line 488
    input = input.view((-1, (*input.shape[-3:])))
                             ^
SyntaxError: can't use starred expression here

**Comment by ichsan2895** [comment]
AFAIK, I think torch <= 1.6 doesn't support in python 3.9. Google colab uses python 3.9. So, my suggestion is using torch that supported by python 3.9, but please don't use torch 2.0 since some dependencies don't compatible with it.

**Comment by CUTEPKQ** [comment]
use the command
`! sudo update-alternatives --config python3`
then, select the python3.8

**Comment by CUTEPKQ** [comment]
before git clone, use the command
! sudo update-alternatives --config python3
then, select the python3.8
