### ISSUE TITLE
nerf-w train.py problem

### ISSUE THREAD

**Issue by fl990812** [kwea123/nerf_pl#218]
i use python train.py   --root_dir /data/kb/fl/nerf_pl-nerfw/brandenburg_gate/ --dataset_name phototourism   --img_downscale 8 --use_cache --N_importance 64 --N_samples 64   --encode_a --encode_t --beta_min 0.03 --N_vocab 1500   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine --exp_name brandenburg_scale8_nerfw
but
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    main(hparams)
  File "train.py", line 213, in main
    trainer.fit(system)
  File "/data/kb/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 493, in fit
    self.accelerator_backend.setup(model)
  File "/data/kb/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 45, in setup
    self.trainer.call_setup_hook(model)
  File "/data/kb/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 895, in call_setup_hook
    model.setup(stage_name)
  File "train.py", line 109, in setup
    self.train_dataset = dataset(split='train', **kwargs)
  File "/data/kb/fl/nerf_pl-nerfw/datasets/phototourism.py", line 38, in __init__
    self.read_meta()
  File "/data/kb/fl/nerf_pl-nerfw/datasets/phototourism.py", line 43, in read_meta
    tsv = glob.glob(os.path.join(self.root_dir, '*.tsv'))[0]
IndexError: list index out of range
why

**Comment by WendyeeWang** [comment]
I have the same error as yours.Did you solve it?

**Comment by BoZhiStudying233** [comment]
I have the same error as yours. Did you solve it?
