### ISSUE TITLE
Support for Google TPU? 

### ISSUE THREAD

**Issue by Shadowphax** [kwea123/nerf_pl#74]
Hi, 

Thank you for developing the repository. Are there possible plans to include TPU support?
**Branch:** Dev

Regards 
Tim

**Comment by kwea123** [comment]
pytorch lightning supports TPU. It should be a quick modification of this function **without modification of anything else**
https://github.com/kwea123/nerf_pl/blob/2ca26add4f85218a97f6825e3eb0b9db19e7bab5/train.py#L167-L177
You can have a look on [pytorch lightning doc](https://pytorch-lightning.readthedocs.io/en/stable/advanced/tpu.html?highlight=tpu) of how to enable it (also upgrade pytorch lightning to latest version if needed).

**Comment by Shadowphax** [comment]
Thank you. 

I have made those changes and it addresses the TPU but unfortunately seems to crash soon after executing.

```
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Exception in device=TPU:6: Cannot access data pointer of Tensor that doesn't have storage
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 523, in tpu_train
    self.run_pretrain_routine(model)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 899, in run_pretrain_routine
    False)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 278, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 447, in evaluation_forward
    output = model.validation_step(*args)
  File "/home/username/nerf_pl/train.py", line 126, in validation_step
    results = self(rays)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/username/nerf_pl/train.py", line 67, in forward
    self.train_dataset.white_back)
  File "/home/username/nerf_pl/models/rendering.py", line 226, in render_rays
    N_importance, det=(perturb==0)).detach()
  File "/home/username/nerf_pl/models/rendering.py", line 42, in sample_pdf
    inds = searchsorted(cdf, u, side='right')
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torchsearchsorted/searchsorted.py", line 51, in searchsorted
    searchsorted_cpu_wrapper(a, v, out, left_side)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    trainer.fit(system)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in fit
    xmp.spawn(self.tpu_train, args=(model,), nprocs=self.num_tpu_cores, start_method=start_method)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 5 terminated with exit code 17
```
