### ISSUE TITLE
Support for TPU

### ISSUE THREAD

**Issue by Shadowphax** [kwea123/nerf_pl#77]
Hi 

I have made the relevant changes to the trainer.py by inserting ```num_tpu_cores = 8 ``` and exported the ```XRT_TPU_CONFIG```. I can also confirm that the train.py executes the TPU as per the monitoring logs of the TPU but then crashes shortly after. 

This issue stems from [https://github.com/kwea123/nerf_pl/issues/74](https://github.com/kwea123/nerf_pl/issues/74)

```
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Exception in device=TPU:6: Cannot access data pointer of Tensor that doesn't have storage
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 523, in tpu_train
    self.run_pretrain_routine(model)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 899, in run_pretrain_routine
    False)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 278, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 447, in evaluation_forward
    output = model.validation_step(*args)
  File "/home/username/nerf_pl/train.py", line 126, in validation_step
    results = self(rays)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/username/nerf_pl/train.py", line 67, in forward
    self.train_dataset.white_back)
  File "/home/username/nerf_pl/models/rendering.py", line 226, in render_rays
    N_importance, det=(perturb==0)).detach()
  File "/home/username/nerf_pl/models/rendering.py", line 42, in sample_pdf
    inds = searchsorted(cdf, u, side='right')
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torchsearchsorted/searchsorted.py", line 51, in searchsorted
    searchsorted_cpu_wrapper(a, v, out, left_side)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    trainer.fit(system)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in fit
    xmp.spawn(self.tpu_train, args=(model,), nprocs=self.num_tpu_cores, start_method=start_method)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/username/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 5 terminated with exit code 17

```

**Comment by kwea123** [comment]
Hi, seen from the error message, it seems you're using `master` branch. I suggest you use `dev` branch since `master` has custom `searchsorted` method, and in `dev` that function is included in native pytorch (so I assume there's a higher chance that it supports TPU calculation...)

Other than this I think I cannot help much because I don't have TPU experience and I don't have access to any TPU resource to test...
